### ISSUE TITLE
[BUG] Missing Vino button in a system

### ISSUE THREAD

**Issue by Havoclivekiller** [cswendrowski/FoundryVTT-ViNo#9]
The button for Vino on Actors seems to be missing in the Level Up Advanced 5th Edition.
![image](https://github.com/cswendrowski/FoundryVTT-ViNo/assets/21118924/e6935ea2-8159-44a5-a4a8-8abdd189c2f9)
It works on other systems. Also, strangely other buttons show up - Item Piles, Companions or Art Gallery but not Vino.

**Comment by p4535992** [comment]
should be solved with version 1.1.2
